add consent case type
nrc-no/core pull request #173
Opened 2021-09-28 16:04 UTC by internetti

2021-09-28 18:31 UTC, nilueps commented on api/pkg/apps/seeder/static.go
> +				Type:  form.Text,
```suggestion
				Type:  form.URL,
```

2021-09-28 18:32 UTC, nilueps requested changes
Looks good, just a little tweak needed

2021-09-29 09:48 UTC, ludydoo approved these changes

2021-09-29 13:21 UTC, shinroo approved these changes

2021-09-29 14:12 UTC, shinroo approved these changes

2021-09-29 14:14 UTC, merged