COR 340 PARTIAL FormsScreenContainer Test
nrc-no/core pull request #263
Opened 2021-12-01 21:14 UTC by nilueps

- setup tests
- add FormsScreen test
- add FormsScreenContainer test

2021-12-02 16:26 UTC, internetti reviewed
you could rebase this on the other COR-340 partial branch, would make this one even smaller. 
just because, if this one contains all the changes that the other one has, that makes the other one redundant

2021-12-02 16:27 UTC, internetti requested changes
can you do another yarn install, the yarn.lock has conflicts

2021-12-03 18:04 UTC, ludydoo commented
`jest.mock("../../src/utils/clients",...`

should be 

`jest.mock("../../src/utils/client",... `

2021-12-06 14:02 UTC, nilueps commented
can we rename that in another ticket?

2021-12-06 15:49 UTC, ludydoo commented on web/app/frontend/src/components/screens/FormsScreen.tsx
> +            {/*<Title>{routes.forms.title}</Title>*/}
Is this supposed to be removed?

2021-12-06 17:17 UTC, ludydoo commented
/lgtm

2021-12-06 17:18 UTC, ludydoo commented
You just need to rebase this one

2021-12-06 17:18 UTC, merged